import jsPDF from 'jspdf';
import { BlogSuggestion } from '../types';

export function generatePDF(suggestions: BlogSuggestion[], businessInfo: { businessName: string; industry: string; location: string }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('SEO Blog Topics Suggestions', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Business Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Business Name: ${businessInfo.businessName}`, margin, yPosition);
  yPosition += 10;
  doc.text(`Industry: ${businessInfo.industry}`, margin, yPosition);
  yPosition += 10;
  doc.text(`Location: ${businessInfo.location}`, margin, yPosition);
  yPosition += 15;

  // Suggestions
  suggestions.forEach((suggestion, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Title with word wrap
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(`${index + 1}. ${suggestion.title}`, contentWidth);
    doc.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * 8;

    // Description with proper word wrap
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    const descriptionLines = doc.splitTextToSize(suggestion.description, contentWidth);
    doc.text(descriptionLines, margin, yPosition);
    yPosition += descriptionLines.length * 7;

    // Keywords with word wrap
    doc.setFont('helvetica', 'bold');
    doc.text('Keywords:', margin, yPosition);
    doc.setFont('helvetica', 'normal');
    const keywordsText = suggestion.keywords.join(', ');
    const keywordLines = doc.splitTextToSize(keywordsText, contentWidth - 30);
    doc.text(keywordLines, margin + 30, yPosition);
    yPosition += keywordLines.length * 7;

    // Additional Info
    const infoText = `Reading Time: ${suggestion.estimatedReadTime} minutes | Difficulty: ${suggestion.difficulty}`;
    const infoLines = doc.splitTextToSize(infoText, contentWidth);
    doc.text(infoLines, margin, yPosition);
    yPosition += infoLines.length * 7 + 13;
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128);
  doc.text('Generated by SEO Blog Wizard', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc;
}