import { jsPDF } from 'jspdf';
import { ContentStrategy } from '../types';

export function generateStrategyPDF(strategy: ContentStrategy, businessInfo: { 
  businessName: string; 
  industry: string; 
  platform: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = 20;

  // Helper function for text wrapping
  const addWrappedText = (text: string, y: number, fontSize: number = 12) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    return y + (lines.length * (fontSize * 0.5));
  };

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(`${businessInfo.platform} Content Strategy`, margin, yPosition);
  yPosition += 15;

  // Business Info
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${businessInfo.businessName} - ${businessInfo.industry}`, margin, yPosition);
  yPosition += 20;

  // Overview
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Strategy Overview', margin, yPosition);
  yPosition += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  yPosition = addWrappedText(strategy.overview, yPosition) + 15;

  // Target Audience
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Target Audience', margin, yPosition);
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  yPosition = addWrappedText(`Demographics: ${strategy.targetAudience.demographics}`, yPosition) + 5;
  yPosition = addWrappedText(`Interests: ${strategy.targetAudience.interests.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Pain Points: ${strategy.targetAudience.painPoints.join(', ')}`, yPosition) + 15;

  // Add new page if needed
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  // Content Plan
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Content Plan', margin, yPosition);
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  yPosition = addWrappedText(`Content Types: ${strategy.contentPlan.types.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Topics: ${strategy.contentPlan.topics.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Best Practices: ${strategy.contentPlan.bestPractices.join(', ')}`, yPosition) + 15;

  // Add new page if needed
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  // Posting Schedule
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Posting Schedule', margin, yPosition);
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  yPosition = addWrappedText(`Frequency: ${strategy.postingSchedule.frequency}`, yPosition) + 5;
  yPosition = addWrappedText(`Best Times: ${strategy.postingSchedule.bestTimes.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Consistency: ${strategy.postingSchedule.consistency}`, yPosition) + 15;

  // Add new page if needed
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  // Engagement Strategy
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Engagement Strategy', margin, yPosition);
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  yPosition = addWrappedText(`Tactics: ${strategy.engagement.tactics.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Response Guidelines: ${strategy.engagement.responses.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Monitoring: ${strategy.engagement.monitoring.join(', ')}`, yPosition) + 15;

  // Add new page if needed
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  // Metrics and KPIs
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Metrics and KPIs', margin, yPosition);
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  yPosition = addWrappedText(`KPIs: ${strategy.metrics.kpis.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Tools: ${strategy.metrics.tools.join(', ')}`, yPosition) + 5;
  yPosition = addWrappedText(`Goals: ${strategy.metrics.goals.join(', ')}`, yPosition) + 15;

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128);
  doc.text('Generated by SEO Wizard', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc;
}